# Deployment_1
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app1
spec:
  replicas: 4
  selector: 
    matchLabels: 
       app: app1
  template: 
    metadata:
      labels:
        app: app1
    spec:  
      containers:
        - name: app1
          image: httpd
          ports: 
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec: 
  selector:
   app: app1
  ports: 
   - port: 80
  type: NodePort
---

# Deployment 2
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app2
spec:
  replicas: 5
  selector: 
    matchLabels: 
       app: app2
  template: 
    metadata:
      labels:
        app: app2
    spec:  
      containers:
        - name: app2
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec: 
  selector:
   app: app2
  ports: 
   - port: 8080
  type: NodePort
---
# Deployment 3

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app3
spec:
  replicas: 5
  selector: 
    matchLabels: 
       app: app3
  template: 
    metadata:
      labels:
        app: app3
    spec:  
      containers:
        - name: app3
          image: gcr.io/google-samples/hello-app:2.0 
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app3
spec: 
  selector:
   app: app3
  ports: 
   - port: 8080
  type: NodePort
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multiapp-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: youssefshawky.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app1
                port:
                  number: 80
          - path: /app2
            pathType: Prefix
            backend:
              service:
                name: app2
                port:
                  number: 8080
          - path: /app3
            pathType: Prefix
            backend:
              service:
                name: app3
                port:
                  number: 8080                
                  